use serde::{Serialize, Serializer};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
#[repr(i16)]
pub enum Packets {
    OsuChangeAction = 0,
    OsuSendPublicMessage = 1,
    OsuLogout = 2,
    OsuRequestStatusUpdate = 3,
    OsuPing = 4,
    ChoUserId = 5,
    ChoSendMessage = 7,
    ChoPong = 8,
    ChoHandleIrcChangeUsername = 9,
    ChoHandleIrcQuit = 10,
    ChoUserStats = 11,
    ChoUserLogout = 12,
    ChoSpectatorJoined = 13,
    ChoSpectatorLeft = 14,
    ChoSpectateFrames = 15,
    OsuStartSpectating = 16,
    OsuStopSpectating = 17,
    OsuSpectateFrames = 18,
    ChoVersionUpdate = 19,
    OsuErrorReport = 20,
    OsuCantSpectate = 21,
    ChoSpectatorCantSpectate = 22,
    ChoGetAttention = 23,
    ChoNotification = 24,
    OsuSendPrivateMessage = 25,
    ChoUpdateMatch = 26,
    ChoNewMatch = 27,
    ChoDisposeMatch = 28,
    OsuPartLobby = 29,
    OsuJoinLobby = 30,
    OsuCreateMatch = 31,
    OsuJoinMatch = 32,
    OsuPartMatch = 33,
    ChoToggleBlockNonFriendDms = 34,
    ChoMatchJoinSuccess = 36,
    ChoMatchJoinFail = 37,
    OsuMatchChangeSlot = 38,
    OsuMatchReady = 39,
    OsuMatchLock = 40,
    OsuMatchChangeSettings = 41,
    ChoFellowSpectatorJoined = 42,
    ChoFellowSpectatorLeft = 43,
    OsuMatchStart = 44,
    ChoAllPlayersLoaded = 45,
    ChoMatchStart = 46,
    OsuMatchScoreUpdate = 47,
    ChoMatchScoreUpdate = 48,
    OsuMatchComplete = 49,
    ChoMatchTransferHost = 50,
    OsuMatchChangeMods = 51,
    OsuMatchLoadComplete = 52,
    ChoMatchAllPlayersLoaded = 53,
    OsuMatchNoBeatmap = 54,
    OsuMatchNotReady = 55,
    OsuMatchFailed = 56,
    ChoMatchPlayerFailed = 57,
    ChoMatchComplete = 58,
    OsuMatchHasBeatmap = 59,
    OsuMatchSkipRequest = 60,
    ChoMatchSkip = 61,
    ChoUnauthorized = 62, // unused
    OsuChannelJoin = 63,
    ChoChannelJoinSuccess = 64,
    ChoChannelInfo = 65,
    ChoChannelKick = 66,
    ChoChannelAutoJoin = 67,
    OsuBeatmapInfoRequest = 68,
    ChoBeatmapInfoReply = 69,
    OsuMatchTransferHost = 70,
    ChoPrivileges = 71,
    ChoFriendsList = 72,
    OsuFriendAdd = 73,
    OsuFriendRemove = 74,
    ChoProtocolVersion = 75,
    ChoMainMenuIcon = 76,
    OsuMatchChangeTeam = 77,
    OsuChannelPart = 78,
    OsuReceiveUpdates = 79,
    ChoMonitor = 80, // unused
    ChoMatchPlayerSkipped = 81,
    OsuSetAwayMessage = 82,
    ChoUserPresence = 83,
    OsuIrcOnly = 84,
    OsuUserStatsRequest = 85,
    ChoRestart = 86,
    OsuMatchInvite = 87,
    ChoMatchInvite = 88,
    ChoChannelInfoEnd = 89,
    OsuMatchChangePassword = 90,
    ChoMatchChangePassword = 91,
    ChoSilenceEnd = 92,
    OsuTournamentMatchInfoRequest = 93,
    ChoUserSilenced = 94,
    ChoUserPresenceSingle = 95,
    ChoUserPresenceBundle = 96,
    OsuUserPresenceRequest = 97,
    OsuUserPresenceRequestAll = 98,
    OsuToggleBlockNonFriendDms = 99,
    ChoUserDmBlocked = 100,
    ChoTargetIsSilenced = 101,
    ChoVersionUpdateForced = 102,
    ChoSwitchServer = 103,
    ChoAccountRestricted = 104,
    ChoRtx = 105, // unused
    ChoMatchAbort = 106,
    ChoSwitchTournamentServer = 107,
    OsuTournamentJoinMatchChannel = 108,
    OsuTournamentLeaveMatchChannel = 109,
}

impl Serialize for Packets {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_i16(*self as i16)
    }
}
